### ISSUE TITLE
Enemy Air Fighter Power Not Showing In Compass

### ISSUE THREAD

**Issue by Classiick** [silfumus/ElectronicObserver#11]
See image below: enemy air fighter power is not showing in the compass feature - it's always zero. Also showing zero planes for enemy ships in their equipment slots. But Battle feature is showing some plane numbers/stats, if that's relevant.

![2017-01-20 07_54_36-greenshot](https://cloud.githubusercontent.com/assets/25242011/22140807/9a754fe8-dee6-11e6-9b10-3f87d04dc92e.png)

**Comment by silfumus** [comment]
Have you double-checked? I couldn't replicate your issue on a fresh install of EO.

I suppose one of the enemy ship/fleet entry for that node is in error. Try doing this:
1. Close Electronic Observer
2. Go to `.\ElectronicObserver\Record`
3. Try deleting/renaming `EnemyFleetRecord.csv` (and also `ShipParameterRecord.csv` if it's still happening) to something else
4. Start Electronic Observer again

**Comment by Classiick** [comment]
I noticed it for a few weeks or so on several nodes, even after the 2.5.2 update, but I never bothered to report it until now.
 
It looks like your solution has worked though - I was probably retaining some old dodgy files/records back from when I was trying to transfer my records from RyuuKitsune's EO to your EO.
 
Thanks!
