### ISSUE TITLE
Quest progress not resetting on new day/week.

### ISSUE THREAD

**Issue by tallos** [silfumus/ElectronicObserver#31]
The progress for quests is not resetting properly if EO is running when the daily/weekly quest reset happens in 3.0.4. Quests that should not be visible because the prereqs are not met are also left visible if partially completed the previous day/week

Ex: I have not sortied yet after this weekly reset, yet this is my quest screen after 2 expeditions returned, 2 ships bucketed, and 3 ships sent to docks while preparing to sortie. bw6, bw7 both should not be visible because prereqs are not completed and be at 0 progress, bd1, c2d1, e4d2, and f5d1 should all have 0 progress, d2d1 should be at 2/3 progress, 
![quest updates](https://user-images.githubusercontent.com/3512963/33531520-2de1a41a-d85c-11e7-91ad-ee8b6645d53e.PNG)

**Comment by silfumus** [comment]
The last week quests should disappear after you visited the ingame quest page and repopulate the quest list. If you've done that and the issue still persist, you could reset the quests data by right-clicking at the EO quest window and choose `Reset`.
Meanwhile, I'll check whether this is a bug on the fork or not.

Thanks for your report.

**Comment by tallos** [comment]
That was what it looked like after visiting the ingame quest page to repopulate the list. I do not think it was happening in 3.0.2 and before, but i was not paying much attention to quests at the time because of the event so i could be mistaken.

**Comment by tallos** [comment]
Possibly related, but the clock in the bottom right is showing the local time being 2 hours ahead when set to local time, ie time currently is 2:07EST, but EO says the time is 4:07. When time is set to Quest/PVP it shows the correct countdown till resets.

**Comment by silfumus** [comment]
Ah my bad, it's supposed to be server time (JST +0900). If you're 2 hours behind, you should be in timezone UTC +0700.
Also within "local time" mode, you could see pvp, quest reset, and maintenance countdown from the tooltip (hover on the clock).

Lastly, I was busy on completing the event so I haven't had time to follow up on the issue, sorry about that.

**Comment by tallos** [comment]
no problem, just wanted to make sure you where aware of them, the quest thing is just a minor inconveniecne since i can just reset the ones that bug out individually.

**Comment by tallos** [comment]
I think i found what is causing quest progress to not reset properly at least in v 3.1.1.

The bug happens to me regularly if I idle when the reset is happening and go straight to the quest screen after reset without visiting the games main screen first. 
If i do a fresh visit to the main screen before going to the quest page everything seems to reset properly.
