### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wumbo60** [silfumus/ElectronicObserver#43]
![czcz](https://user-images.githubusercontent.com/19922293/44523939-b6a22980-a716-11e8-8c1d-c099f9578f9d.png)

i got this from the start, even already clear cache 

also, thanks for your hard work

**Comment by silfumus** [comment]
You're using the old release which still uses IE11. It's incompatible with KanColle Phase 2.
Download the new version from `https://github.com/silfumus/ElectronicObserver/releases/tag/v3.1.2.1` which now uses Chromium-based browser.

I'm not planning to make EO auto-update to this version since the main version haven't implemented it.

**Comment by wumbo60** [comment]
![czcz](https://user-images.githubusercontent.com/19922293/44619151-d4a98e80-a8bc-11e8-9bd1-dee54c9a10f5.png)

i've already download chromium also and when open new EO i just got blank screen

**Comment by wumbo60** [comment]
![czcz](https://user-images.githubusercontent.com/19922293/44623104-a26e5000-a901-11e8-9ff5-b7de80e34439.png)

already update C++ and net  framework, dmm logon still can't show up and got this notification

**Comment by silfumus** [comment]
Not sure what's the problem if you have the latest `.Net` and `Visual C++` installed.

I think I'm going to try searching for the problem myself, please state your installed `Operating System`, `.Net`, and `Visual C++` version.

**Comment by wumbo60** [comment]
Win 7 Ultimate 64 bit, Net 4.7.2.1 

![silfu](https://user-images.githubusercontent.com/19922293/44669799-e4130e00-aa5b-11e8-86ff-dfba1c172ee9.PNG)

thanks mate

**Comment by silfumus** [comment]
Just tested a clean install of `Windows 7` with `.Net 4.7.2` and `Visual C++ 2017 x86`, still couldn't encounter the error.

I've uploaded a new version for you to test: [ElectronicObserver400beta.zip](https://github.com/silfumus/ElectronicObserver/releases/download/v3.1.2.1/ElectronicObserver400beta.zip).
If it's still gives you the same error, please click the `Details` button and paste the content here.

**Comment by silfumus** [comment]
Also on https://github.com/silfumus/ElectronicObserver/issues/43#issuecomment-415972328, this may be related to a bug that I've found.

For some reason, the browser shows blank window but if you click `More Options (...)` -> `Go to ...` and go to any address (e.g: `http://www.dmm.com/netgame/social/-/gadgets/=/app_id=854854/`), it load the page correctly.

**Comment by wumbo60** [comment]
![fgdgd](https://user-images.githubusercontent.com/19922293/44786842-5dcc0880-abd0-11e8-8581-20b06a8af7ca.png)
thanks a lot mate, finally i can login , love your works
