### ISSUE TITLE
hp bar issue

### ISSUE THREAD

**Issue by homuhomu123** [silfumus/ElectronicObserver#45]
New update broke the hp bar.

![hpbar broke](https://user-images.githubusercontent.com/42673022/44583069-5ecaf780-a7d6-11e8-9d8d-0624eef358e6.jpg)

**Comment by myangelkamikaze** [comment]
That's a problem with the game itself, enable hardware acceleration and it will get fixed.

**Comment by silfumus** [comment]
Yeah. the problem also happens in chrome if hardware acceleration is not enabled.
Closing the issue until it's fixed in the upstream.
