### ISSUE TITLE
Game window becomes misaligned 

### ISSUE THREAD

**Issue by silfumus** [silfumus/ElectronicObserver#48]
Submitter: EBXXIV
Email: -omitted-@gmail.com
The first time I run the .exe after extracting from the .zip there is no issue.
The second time running the .exe, whether I load a layout or not, the alignment of the game visuals are shifted down about 5%, with a thin black bar at the top. The buttons aren't affected, so the visuals don't perfectly line up with the buttons. I can't play the game like this and I'm resorting to KC3 until this works properly for me again.
Here's a screenshot of my game window https://puu.sh/BoXbj/b8a610ce65.png

**Comment by myangelkamikaze** [comment]
It's a high DPI problem cefsharp has:

https://github.com/andanteyk/ElectronicObserver/issues/236

For win10 you can fix it like this:
1) Open "Properties" of EOBrowser.exe from right click menu
2) Open "Change high DPI settings" from compatibility tab
3) Tick "High DPI scaling override"
4) Select "Application" from the drop list

**Comment by EBXXIV** [comment]
Selecting "System" from the drop list worked for me.
Thank you for the hint!
