### ISSUE TITLE
Node naming

### ISSUE THREAD

**Issue by myangelkamikaze** [silfumus/ElectronicObserver#49]
Node names on compass are all messed up due to all the phase 2 changes, would probably be a good idea to just remove this translation and let it display the ID like the Japanese version till a brave soul comes around to update all the nodes. In the case that someone does update them I'd like to request a setting to display the original ID instead of the node name.

**Comment by silfumus** [comment]
Go to `Settings\Configuration.xml`, set `<UseOriginalNodeId>` to true.
Sorry for not including the setting into the GUI.

**Comment by myangelkamikaze** [comment]
All good, thank you~
