### ISSUE TITLE
4.0.1 dont open while 4.0.0 does

### ISSUE THREAD

**Issue by silfumus** [silfumus/ElectronicObserver#56]
Submitter: ntolegna
Email: kappadresse@gmail.com
Hi ! Me and an another person from r/kancolle are unable to open 4.0.1 version. I personnaly tried 4.0.0 and it opened ! I dont know what's the problem, hope it help a bit. Bye~

**Comment by myangelkamikaze** [comment]
I sure hope this isn't people downloading 4.0.1 without having the browser, but I noticed the release was already updated just in case.
