### ISSUE TITLE
No bgm sound.

### ISSUE THREAD

**Issue by silfumus** [silfumus/ElectronicObserver#58]
Submitter: ayase
Theres no bgm sound in the game, no sortie sound, no boss sound, no office bgm sound. There's only buttom sound and kanmusus voices.

**Comment by myangelkamikaze** [comment]
Connection problems? Those take slightly longer to load so on worse connections they might not load before everything is over. 

There are also settings to change the BGM, were you changing anything there and forgot about it?

Did you make sure to turn them on in the game option menu?

**Comment by 9D818F848C** [comment]
C:\Users\you\AppData\Local\ElectronicObserver\CEF\

delete "cache"
