### ISSUE TITLE
32 bit

### ISSUE THREAD

**Issue by myangelkamikaze** [silfumus/ElectronicObserver#59]
Is there a reason why it's 32bit? The Japanese version has moved to 64bit which also fixed some white screen problems it seems.

https://github.com/andanteyk/ElectronicObserver/issues/242#issuecomment-418007508

**Comment by silfumus** [comment]
I was planning to keep compatability with 32-bit systems.
Looks like it's not really needed.
---
Just got back and realized andanteyk doesn't develop anymore.
Any clue to which main development fork I should follow?

**Comment by silfumus** [comment]
Assumption.
Haven't opened KC yet, but I thought there are some breaking changes judging from the fork histories.
