### ISSUE TITLE
Incorrect battle result (Combined fleet with friend fleet only)

### ISSUE THREAD

**Issue by silfumus** [silfumus/ElectronicObserver#60]
Submitter: [GM]NeverWinter
I dont know if anyone had report this or not but just in case since im new to this.

Detail in picture: https://imgur.com/GVA2kia
=============
Battle log:

Western Operation Area Ceylon Island (42-3) [Hard] Node: 25 (Boss)
#3 HP: 1123 / 1400
深海前線葉艦棲泊地

◆ Kidou Butai Combined Fleet Day Battle ◆
== Participant ==
 - Main Fleet -
#1: CV Akagi Kai Lv. 92 HP: 77 / 77 - FP:54, Torp:0, AA:79, Armor:79
　Reppuu (601 Air Group) >>, Shiden Kai 4 >>, Suisei Model 22 (634 Air Group) |, Shiden Kai 4 >>
#2: CV Hiryuu Kai Ni Lv. 98 HP: 23 / 67 - FP:64, Torp:0, AA:82, Armor:76
　Zero Fighter Model 53 (Iwamoto Squadron)+10 >>, Type 97 Torpedo Bomber (Skilled) >>, Type 99 Dive Bomber (Skilled) >>, Fw 190T Kai >>
#3: CV Souryuu Kai Ni Lv. 99 HP: 67 / 67 - FP:57, Torp:0, AA:84, Armor:75
　Reppuu Kai >>, Suisei (601 Air Group) >>, Re.2005 Kai >>, Saiun >>
#4: CAV Chikuma Kai Ni Lv. 81 HP: 58 / 58 - FP:77, Torp:83, AA:83, Armor:79
　20.3cm (No.3) Twin Gun, 20.3cm (No.2) Twin Gun, Type 2 Seaplane Fighter Kai (Skilled) >>, Type 0 Recon Seaplane Model 11B (Skilled) >>
#5: CA Kako Kai Ni Lv. 78 HP: 52 / 52 - FP:78, Torp:77, AA:47, Armor:72
　20.3cm (No.2) Twin Gun, 20.3cm (No.2) Twin Gun+1, Type 0 Recon Seaplane Model 11B (Skilled) >>, FuMO25 RADAR
#6: SSV I-14 Kai Lv. 72 HP: 22 / 22 - FP:12, Torp:68, AA:0, Armor:23
　New High Pressure-Temperature Steam Boiler, New High Pressure-Temperature Steam Boiler, Improved Kanhon Turbine

- Escort Fleet -
#1: CL Abukuma Kai Ni Lv. 99 HP: 7 / 45 - FP:56, Torp:94, AA:78, Armor:68
　Kouhyouteki, 61cm Quintuple (Oxygen) Torpedo, 61cm Triple (Oxygen) Torpedo
#2: DD Fubuki Kai Ni Lv. 99 HP: 31 / 31 - FP:59, Torp:88, AA:78, Armor:50
　10cm Twin High-angle Gun+AAFD, 10cm Twin High-angle Gun+AAFD, Type 13 Air RADAR Kai, 12cm 30-tube Rocket Launcher Kai 2
#3: CA Choukai Kai Ni Lv. 83 HP: 57 / 57 - FP:85, Torp:86, AA:70, Armor:78
　20.3cm (No.2) Twin Gun, 20.3cm (No.2) Twin Gun, Type 98 Recon Seaplane (Night Recon) >>, Type 3 Shell
#4: DD Hatsushimo Kai Ni Lv. 99 HP: 32 / 32 - FP:59, Torp:85, AA:81, Armor:55
　61cm Quadruple (Oxygen) Torpedo, 61cm Quadruple (Oxygen) Torpedo, Star Shell
#5: CLT Kitakami Kai Ni Lv. 99 HP: 43 / 43 - FP:63, Torp:139, AA:49, Armor:63
　Kouhyouteki, 61cm Triple (Oxygen) Torpedo, 61cm Triple (Oxygen) Torpedo Mount Late Model, 12cm 30-tube Rocket Launcher Kai 2
#6: DD Kasumi Kai Ni Lv. 99 HP: 31 / 31 - FP:65, Torp:92, AA:72, Armor:52
　61cm Quintuple (Oxygen) Torpedo, 61cm Quadruple (Oxygen) Torpedo Mount Late Model, 61cm Quintuple (Oxygen) Torpedo

- Enemy Main Fleet -
#1: ID:1823 CVL German Escort Princess Lv. 1 HP: 570 / 570 - FP:150, Torp:0, AA:120, Armor:284
　[586] Abyssal Patrolling Attack Hawk Kai 2, [582] Abyssal Night Dive Bomber, [553] 4inch Dual Purpose Gun+CIC, [553] 4inch Dual Purpose Gun+CIC
#2: ID:1766 CVL CVL Nu-Class Kai flagship Lv. 1 HP: 118 / 118 - FP:45, Torp:0, AA:68, Armor:93
　[575] Abyssal Patrolling Attack Hawk Kai, [556] Abyssal Cat Fighter Kai, [557] Abyssal Hell Diver Kai, [558] Abyssal Avenger Torpedo Bomber Kai
#3: ID:1766 CVL CVL Nu-Class Kai flagship Lv. 1 HP: 118 / 118 - FP:45, Torp:0, AA:68, Armor:93
　[575] Abyssal Patrolling Attack Hawk Kai, [556] Abyssal Cat Fighter Kai, [557] Abyssal Hell Diver Kai, [558] Abyssal Avenger Torpedo Bomber Kai
#4: ID:1698 BB BB Summer Princess Lv. 1 HP: 530 / 530 - FP:195, Torp:0, AA:88, Armor:168
　[509] 16inch Triple Gun, [509] 16inch Triple Gun, [512] 12.5inch Twin Secondary Gun, [529] Surface RADAR Mk.II
#5: ID:1595 CA CA Ne-Class elite Lv. 1 HP: 88 / 88 - FP:79, Torp:74, AA:79, Armor:89
　[505] 8inch Triple Gun, [505] 8inch Triple Gun, [515] High-speed Abyssal Torpedo, [525] Abyssal Recon Plane
#6: ID:1595 CA CA Ne-Class elite Lv. 1 HP: 88 / 88 - FP:79, Torp:74, AA:79, Armor:89
　[505] 8inch Triple Gun, [505] 8inch Triple Gun, [515] High-speed Abyssal Torpedo, [525] Abyssal Recon Plane

- Enemy Escort Fleet -
#1: ID:1592 CL CL Tsu-Class elite Lv. 1 HP: 66 / 66 - FP:64, Torp:92, AA:96, Armor:68
　[550] 5inch Twin Dual Purpose Gun, [550] 5inch Twin Dual Purpose Gun, [545] Abyssal SONAR Mk.II, [525] Abyssal Recon Plane
#2: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 66 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#3: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 66 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#4: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 66 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#5: ID:1577 DD DD Ha-Class (Late Type) Lv. 1 HP: 38 / 38 - FP:44, Torp:72, AA:36, Armor:29
　[502] 5inch Twin Gun, [515] High-speed Abyssal Torpedo, [542] Abyssal Depth Charge
#6: ID:1577 DD DD Ha-Class (Late Type) Lv. 1 HP: 38 / 38 - FP:44, Torp:72, AA:36, Armor:29
　[502] 5inch Twin Gun, [515] High-speed Abyssal Torpedo, [542] Abyssal Depth Charge

- Air Base -
第一基地航空隊 [Mission]
　Type 2 Large Flying Boat ||, Type 1 Attack Bomber (Nonaka Squadron) /, Type 1 Attack Bomber Model 34 /, Type 1 Fighter Hayabusa Model II (64th Squadron) >>
第二基地航空隊 [Mission]
　PBY-5A Catalina |, Type 1 Attack Bomber Model 22A ///, Ginga ///, Type 1 Fighter Hayabusa Model IIIA (54th Squadron) >>

== LOS ==
Formation: Fourth Cruising Formation / Enemy Formation: Fourth Cruising Formation
Engagement: Green T
Contact: Success / Enemy Contact: Success

== Land-based Air Attack ==
-- Wave 1 --
Friendly Air Squadrons:
　Type 2 Large Flying Boat x 4, Type 1 Attack Bomber (Nonaka Squadron) x 18, Type 1 Attack Bomber Model 34 x 18, Type 1 Fighter Hayabusa Model II (64th Squadron) x 18
Stage 1: AI
　Friendly: -16/58
　Enemy: -51/351
　Enemy Contact: Abyssal Avenger Torpedo Bomber Kai
Stage 2: 
　Friendly: -6/26
　Enemy: -0/0

Air Squadron Wave 1 → DD Na-Class (Late Type) elite #9
[Torpedo Attack] 130 Critical! ( 66 → 0 )

Air Squadron Wave 1 → DD Ha-Class (Late Type) #12
[Torpedo Attack] 82 Dmg ( 38 → 0 )

-- Wave 2 --
Friendly Air Squadrons:
　Type 2 Large Flying Boat x 4, Type 1 Attack Bomber (Nonaka Squadron) x 18, Type 1 Attack Bomber Model 34 x 18, Type 1 Fighter Hayabusa Model II (64th Squadron) x 18
Stage 1: AI
　Friendly: -11/58
　Enemy: -54/300
Stage 2: 
　Friendly: -6/28
　Enemy: -0/0

Air Squadron Wave 2 → CVL Nu-Class Kai flagship #2
[Torpedo Attack] 13 Dmg ( 118 → 105 )

Air Squadron Wave 2 → BB Summer Princess #4
[Torpedo Attack] 33 Dmg ( 530 → 497 )

-- Wave 3 --
Friendly Air Squadrons:
　PBY-5A Catalina x 4, Type 1 Attack Bomber Model 22A x 18, Ginga x 18, Type 1 Fighter Hayabusa Model IIIA (54th Squadron) x 18
Stage 1: AI-
　Friendly: -24/58
　Enemy: -12/246
　Enemy Contact: Abyssal Avenger Torpedo Bomber Kai
Stage 2: 
　Friendly: -6/22
　Enemy: -0/0

Air Squadron Wave 3 → DD Na-Class (Late Type) elite #8
[Torpedo Attack] 41 Dmg ( 66 → 25 )

Air Squadron Wave 3 → DD Na-Class (Late Type) elite #10
[Torpedo Attack] 53 Dmg ( 66 → 13 )

-- Wave 4 --
Friendly Air Squadrons:
　PBY-5A Catalina x 4, Type 1 Attack Bomber Model 22A x 18, Ginga x 18, Type 1 Fighter Hayabusa Model IIIA (54th Squadron) x 18
Stage 1: AI-
　Friendly: -22/58
　Enemy: -3/234
Stage 2: 
　Friendly: -0/22
　Enemy: -0/0

Air Squadron Wave 4 → DD Na-Class (Late Type) elite #10
[Torpedo Attack] 27 Dmg ( 13 → 0 )

Air Squadron Wave 4 → DD Ha-Class (Late Type) #11
[Torpedo Attack] 124 Dmg ( 38 → 0 )

== Air Battle ==
Stage 1: AS
　Friendly: -24/223
　Enemy: -99/223
　Contact: Type 0 Recon Seaplane Model 11B (Skilled)
　Enemy Contact: Abyssal Recon Plane
Stage 2: AACI type #5 ( Fubuki Kai Ni Lv. 99, High-Angle Gun+AAFDx2/Radar )
　Friendly: -18/94
　Enemy: -68/104

Enemy Air Squadron → Souryuu Kai Ni #3
[Torpedo + Bombing Attack] 6 Dmg ( 67 → 61 )

Enemy Air Squadron → Kasumi Kai Ni #12
[Torpedo Attack] 0 Dmg

Friendly Air Squadron → CVL Nu-Class Kai flagship #2
[Bombing Attack] 0 Dmg

Friendly Air Squadron → CA Ne-Class elite #5
[Bombing Attack] 5 Dmg ( 88 → 83 )

Friendly Air Squadron → DD Na-Class (Late Type) elite #8
[Torpedo + Bombing Attack] 2 Dmg ( 25 → 23 )

== Opening Torpedo Salvo ==
Abukuma Kai Ni #7 → CVL Nu-Class Kai flagship #2
<Protected> Miss

Kitakami Kai Ni #11 → DD Na-Class (Late Type) elite #8
110 Dmg ( 23 → 0 )

== Shelling, 1st Round ==
Akagi Kai #1 → CA Ne-Class elite #6
[Air Attack] 79 Dmg ( 88 → 9 )

German Escort Princess #1 → I-14 Kai #6
[Air Attack] 12 Dmg ( 22 → 10 )

Chikuma Kai Ni #4 → CVL Nu-Class Kai flagship #2
[Shelling] 63 Dmg ( 105 → 42 )

CVL Nu-Class Kai flagship #3 → I-14 Kai #6
[Air Attack] Miss

Kako Kai Ni #5 → CA Ne-Class elite #6
[DA] 58 Dmg , 151 Critical! ( 9 → 0 )

BB Summer Princess #4 → Chikuma Kai Ni #4
[Shelling] Miss

Souryuu Kai Ni #3 → CA Ne-Class elite #5
[Air Attack] Miss

CA Ne-Class elite #5 → Chikuma Kai Ni #4
[Shelling] <Protected> Miss

== Shelling, 2nd Round ==
Choukai Kai Ni #9 → CL Tsu-Class elite #7
[Shelling] 50 Dmg ( 66 → 16 )

CL Tsu-Class elite #7 → Kitakami Kai Ni #11
[Shelling] 3 Dmg ( 43 → 40 )

Kitakami Kai Ni #11 → CL Tsu-Class elite #7
[Shelling] 50 Critical! ( 16 → 0 )

== Closing Torpedo Salvo ==
Fubuki Kai Ni #8 → CVL Nu-Class Kai flagship #3
33 Dmg ( 118 → 85 )

Choukai Kai Ni #9 → CA Ne-Class elite #5
29 Dmg ( 83 → 54 )

Hatsushimo Kai Ni #10 → BB Summer Princess #4
54 Critical! ( 497 → 443 )

Kitakami Kai Ni #11 → CVL Nu-Class Kai flagship #2
90 Dmg ( 42 → 0 )

Kasumi Kai Ni #12 → BB Summer Princess #4
62 Critical! ( 443 → 381 )

== Shelling, 3rd Round ==
Akagi Kai #1 → BB Summer Princess #4
[Air Attack] 21 Dmg ( 381 → 360 )

German Escort Princess #1 → I-14 Kai #6
[Air Attack] 5 Dmg ( 10 → 5 )

CVL Nu-Class Kai flagship #3 → Fubuki Kai Ni #8
[Air Attack] 23 Dmg ( 31 → 8 )

Souryuu Kai Ni #3 → CVL Nu-Class Kai flagship #3
[Air Attack] 71 Dmg ( 85 → 14 )

BB Summer Princess #4 → Chikuma Kai Ni #4
[Shelling] <Protected> 29 Dmg ( 58 → 29 )

Chikuma Kai Ni #4 → CVL Nu-Class Kai flagship #3
[Shelling] 21 Dmg ( 14 → 0 )

CA Ne-Class elite #5 → Hiryuu Kai Ni #2
[Shelling] Miss

Kako Kai Ni #5 → CA Ne-Class elite #5
[DA] 175 Critical! , 60 Dmg ( 54 → 0 )

== Battle Finished ==
 - Main Fleet -
#1: Akagi Kai HP: (77 → 77)/77 (0)
#2: Hiryuu Kai Ni HP: (23 → 23)/67 (0)
#3: Souryuu Kai Ni HP: (67 → 61)/67 (-6)
#4: Chikuma Kai Ni HP: (58 → 29)/58 (-29)
#5: Kako Kai Ni HP: (52 → 52)/52 (0)
#6: I-14 Kai HP: (22 → 5)/22 (-17)

- Escort Fleet -
#7: Abukuma Kai Ni HP: (7 → 7)/45 (0)
#8: Fubuki Kai Ni HP: (31 → 8)/31 (-23)
#9: Choukai Kai Ni HP: (57 → 57)/57 (0)
#10: Hatsushimo Kai Ni HP: (32 → 32)/32 (0)
#11: Kitakami Kai Ni HP: (43 → 40)/43 (-3)
#12: Kasumi Kai Ni HP: (31 → 31)/31 (0)

- Enemy Main Fleet -
#1: German Escort Princess HP: (570 → 570)/570 (0)
#2: CVL Nu-Class Kai flagship HP: (118 → 0)/118 (-166)
#3: CVL Nu-Class Kai flagship HP: (118 → 0)/118 (-125)
#4: BB Summer Princess HP: (530 → 360)/530 (-170)
#5: CA Ne-Class elite HP: (88 → 0)/88 (-269)
#6: CA Ne-Class elite HP: (88 → 0)/88 (-288)

- Enemy Escort Fleet -
#7: CL Tsu-Class elite HP: (66 → 0)/66 (-100)
#8: DD Na-Class (Late Type) elite HP: (66 → 0)/66 (-153)
#9: DD Na-Class (Late Type) elite HP: (66 → 0)/66 (-130)
#10: DD Na-Class (Late Type) elite HP: (66 → 0)/66 (-80)
#11: DD Ha-Class (Late Type) HP: (38 → 0)/38 (-124)
#12: DD Ha-Class (Late Type) HP: (38 → 0)/38 (-82)

◆ Enemy Combined Fleet Night Battle ◆
== Participant ==
 - Main Fleet -
#1: CV Akagi Kai Lv. 92 HP: 77 / 77 - FP:54, Torp:0, AA:79, Armor:79
　Reppuu (601 Air Group) >>, Shiden Kai 4 >>, Suisei Model 22 (634 Air Group) |, Shiden Kai 4 >>
#2: CV Hiryuu Kai Ni Lv. 98 HP: 23 / 67 - FP:64, Torp:0, AA:82, Armor:76
　Zero Fighter Model 53 (Iwamoto Squadron)+10 >>, Type 97 Torpedo Bomber (Skilled) >>, Type 99 Dive Bomber (Skilled) >>, Fw 190T Kai >>
#3: CV Souryuu Kai Ni Lv. 99 HP: 61 / 67 - FP:57, Torp:0, AA:84, Armor:75
　Reppuu Kai >>, Suisei (601 Air Group) >>, Re.2005 Kai >>, Saiun >>
#4: CAV Chikuma Kai Ni Lv. 81 HP: 29 / 58 - FP:77, Torp:83, AA:83, Armor:79
　20.3cm (No.3) Twin Gun, 20.3cm (No.2) Twin Gun, Type 2 Seaplane Fighter Kai (Skilled) >>, Type 0 Recon Seaplane Model 11B (Skilled) >>
#5: CA Kako Kai Ni Lv. 78 HP: 52 / 52 - FP:78, Torp:77, AA:47, Armor:72
　20.3cm (No.2) Twin Gun, 20.3cm (No.2) Twin Gun+1, Type 0 Recon Seaplane Model 11B (Skilled) >>, FuMO25 RADAR
#6: SSV I-14 Kai Lv. 72 HP: 5 / 22 - FP:12, Torp:68, AA:0, Armor:23
　New High Pressure-Temperature Steam Boiler, New High Pressure-Temperature Steam Boiler, Improved Kanhon Turbine

- Escort Fleet -
#1: CL Abukuma Kai Ni Lv. 99 HP: 7 / 45 - FP:56, Torp:94, AA:78, Armor:68
　Kouhyouteki, 61cm Quintuple (Oxygen) Torpedo, 61cm Triple (Oxygen) Torpedo
#2: DD Fubuki Kai Ni Lv. 99 HP: 8 / 31 - FP:59, Torp:88, AA:78, Armor:50
　10cm Twin High-angle Gun+AAFD, 10cm Twin High-angle Gun+AAFD, Type 13 Air RADAR Kai, 12cm 30-tube Rocket Launcher Kai 2
#3: CA Choukai Kai Ni Lv. 83 HP: 57 / 57 - FP:85, Torp:86, AA:70, Armor:78
　20.3cm (No.2) Twin Gun, 20.3cm (No.2) Twin Gun, Type 98 Recon Seaplane (Night Recon) >>, Type 3 Shell
#4: DD Hatsushimo Kai Ni Lv. 99 HP: 32 / 32 - FP:59, Torp:85, AA:81, Armor:55
　61cm Quadruple (Oxygen) Torpedo, 61cm Quadruple (Oxygen) Torpedo, Star Shell
#5: CLT Kitakami Kai Ni Lv. 99 HP: 40 / 43 - FP:63, Torp:139, AA:49, Armor:63
　Kouhyouteki, 61cm Triple (Oxygen) Torpedo, 61cm Triple (Oxygen) Torpedo Mount Late Model, 12cm 30-tube Rocket Launcher Kai 2
#6: DD Kasumi Kai Ni Lv. 99 HP: 31 / 31 - FP:65, Torp:92, AA:72, Armor:52
　61cm Quintuple (Oxygen) Torpedo, 61cm Quadruple (Oxygen) Torpedo Mount Late Model, 61cm Quintuple (Oxygen) Torpedo

- Enemy Main Fleet -
#1: ID:1823 CVL German Escort Princess Lv. 1 HP: 570 / 570 - FP:150, Torp:0, AA:120, Armor:284
　[586] Abyssal Patrolling Attack Hawk Kai 2, [582] Abyssal Night Dive Bomber, [553] 4inch Dual Purpose Gun+CIC, [553] 4inch Dual Purpose Gun+CIC
#2: ID:1766 CVL CVL Nu-Class Kai flagship Lv. 1 HP: 0 / 118 - FP:45, Torp:0, AA:68, Armor:93
　[575] Abyssal Patrolling Attack Hawk Kai, [556] Abyssal Cat Fighter Kai, [557] Abyssal Hell Diver Kai, [558] Abyssal Avenger Torpedo Bomber Kai
#3: ID:1766 CVL CVL Nu-Class Kai flagship Lv. 1 HP: 0 / 118 - FP:45, Torp:0, AA:68, Armor:93
　[575] Abyssal Patrolling Attack Hawk Kai, [556] Abyssal Cat Fighter Kai, [557] Abyssal Hell Diver Kai, [558] Abyssal Avenger Torpedo Bomber Kai
#4: ID:1698 BB BB Summer Princess Lv. 1 HP: 360 / 530 - FP:195, Torp:0, AA:88, Armor:168
　[509] 16inch Triple Gun, [509] 16inch Triple Gun, [512] 12.5inch Twin Secondary Gun, [529] Surface RADAR Mk.II
#5: ID:1595 CA CA Ne-Class elite Lv. 1 HP: 0 / 88 - FP:79, Torp:74, AA:79, Armor:89
　[505] 8inch Triple Gun, [505] 8inch Triple Gun, [515] High-speed Abyssal Torpedo, [525] Abyssal Recon Plane
#6: ID:1595 CA CA Ne-Class elite Lv. 1 HP: 0 / 88 - FP:79, Torp:74, AA:79, Armor:89
　[505] 8inch Triple Gun, [505] 8inch Triple Gun, [515] High-speed Abyssal Torpedo, [525] Abyssal Recon Plane

- Enemy Escort Fleet -
#1: ID:1592 CL CL Tsu-Class elite Lv. 1 HP: 0 / 66 - FP:64, Torp:92, AA:96, Armor:68
　[550] 5inch Twin Dual Purpose Gun, [550] 5inch Twin Dual Purpose Gun, [545] Abyssal SONAR Mk.II, [525] Abyssal Recon Plane
#2: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 0 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#3: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 0 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#4: ID:1743 DD DD Na-Class (Late Type) elite Lv. 1 HP: 0 / 66 - FP:79, Torp:113, AA:86, Armor:63
　[501] 5inch Single Gun, [501] 5inch Single Gun, [570] High-speed Abyssal Torpedo mod.2
#5: ID:1577 DD DD Ha-Class (Late Type) Lv. 1 HP: 0 / 38 - FP:44, Torp:72, AA:36, Armor:29
　[502] 5inch Twin Gun, [515] High-speed Abyssal Torpedo, [542] Abyssal Depth Charge
#6: ID:1577 DD DD Ha-Class (Late Type) Lv. 1 HP: 0 / 38 - FP:44, Torp:72, AA:36, Armor:29
　[502] 5inch Twin Gun, [515] High-speed Abyssal Torpedo, [542] Abyssal Depth Charge

== 夜戦開始 ==
Searchlight: Hatsushimo Kai Ni Lv. 99 #10

== 友軍艦隊援護 ==
〈Friendly Fleet〉
#1: DD Asakaze Kai Lv. 89 HP: 23 / 23 - 火力42, 雷装69, 対空52, 装甲37
　12cm Single Gun Kai 2, 53cm Twin Torpedo, Type 22 Surface RADAR Kai 4
#2: DD Harukaze Kai Lv. 88 HP: 23 / 23 - 火力38, 雷装68, 対空56, 装甲38
　12cm Single Gun Kai 2, 53cm Twin Torpedo, Type 22 Surface RADAR Kai 4
#3: DD Matsukaze Kai Lv. 87 HP: 23 / 23 - 火力39, 雷装63, 対空43, 装甲35
　12cm Single Gun Kai 2, 53cm Twin Torpedo, Type 22 Surface RADAR Kai 4
#4: DD Hatakaze Kai Lv. 86 HP: 23 / 23 - 火力38, 雷装52, 対空38, 装甲35
　53cm Twin Torpedo, 53cm Twin Torpedo, 53cm Twin Torpedo

Asakaze Kai #1 → BB Summer Princess #4
[駆逐カットイン(主砲/魚雷/電探)] 49 Dmg

Harukaze Kai #2 → German Escort Princess #1
[駆逐カットイン(主砲/魚雷/電探)] 56 Dmg

BB Summer Princess #4 → Harukaze Kai #2
[Shelling] Miss

Matsukaze Kai #3 → BB Summer Princess #4
[Shelling] 28 Dmg

Hatakaze Kai #4 → German Escort Princess #1
[Torpedo Attack] 70 Critical!

== Night Battle ==
Fubuki Kai Ni #8 → German Escort Princess #1
[DA] 31 Critical! , 45 Critical! ( 570 → 494 )

Choukai Kai Ni #9 → German Escort Princess #1
[DA] 238 Critical! , 15 Dmg ( 494 → 241 )

Hatsushimo Kai Ni #10 → German Escort Princess #1
[CI (Torp×2)] 10 Dmg , 43 Dmg ( 241 → 188 )

BB Summer Princess #4 → Kitakami Kai Ni #11
[CI (MG×2+SG)] <Protected> 2 Dmg ( 40 → 38 )

Kitakami Kai Ni #11 → German Escort Princess #1
[CI (Torp×2)] 67 Dmg , 58 Dmg ( 188 → 63 )

Kasumi Kai Ni #12 → BB Summer Princess #4
[Torpedo Attack] 65 Dmg ( 360 → 295 )

== Battle Finished ==
 - Main Fleet -
#1: Akagi Kai HP: (77 → 77)/77 (0)
#2: Hiryuu Kai Ni HP: (23 → 23)/67 (0)
#3: Souryuu Kai Ni HP: (61 → 61)/67 (0)
#4: Chikuma Kai Ni HP: (29 → 29)/58 (0)
#5: Kako Kai Ni HP: (52 → 52)/52 (0)
#6: I-14 Kai HP: (5 → 5)/22 (0)

- Escort Fleet -
#7: Abukuma Kai Ni HP: (7 → 7)/45 (0)
#8: Fubuki Kai Ni HP: (8 → 8)/31 (0)
#9: Choukai Kai Ni HP: (57 → 57)/57 (0)
#10: Hatsushimo Kai Ni HP: (32 → 32)/32 (0)
#11: Kitakami Kai Ni HP: (40 → 38)/43 (-2)
#12: Kasumi Kai Ni HP: (31 → 31)/31 (0)

- Enemy Main Fleet -
#1: German Escort Princess HP: (570 → 63)/570 (-507)
#2: CVL Nu-Class Kai flagship HP: (0 → 0)/118 (0)
#3: CVL Nu-Class Kai flagship HP: (0 → 0)/118 (0)
#4: BB Summer Princess HP: (360 → 295)/530 (-65)
#5: CA Ne-Class elite HP: (0 → 0)/88 (0)
#6: CA Ne-Class elite HP: (0 → 0)/88 (0)

- Enemy Escort Fleet -
#7: CL Tsu-Class elite HP: (0 → 0)/66 (0)
#8: DD Na-Class (Late Type) elite HP: (0 → 0)/66 (0)
#9: DD Na-Class (Late Type) elite HP: (0 → 0)/66 (0)
#10: DD Na-Class (Late Type) elite HP: (0 → 0)/66 (0)
#11: DD Ha-Class (Late Type) HP: (0 → 0)/38 (0)
#12: DD Ha-Class (Late Type) HP: (0 → 0)/38 (0)

◆ Battle Result ◆
Rank: A
MVP (Main Fleet): Kako Kai Ni Lv. 78
MVP (Escort Fleet): Kitakami Kai Ni Lv. 99
Admiral Exp: +375
Ship Exp: +570

Drop: 
　CA Furutaka

**Comment by myangelkamikaze** [comment]
The friend fleet damage doesn't get included in there, this will be fixed in 4.0.2.

**Comment by silfumus** [comment]
https://github.com/silfumus/ElectronicObserver/commit/89a0f4d39ba96fda3fe55b73d0b3fd58089f70f5 Fixed in 4.0.2.
