### ISSUE TITLE
Change "FBB" to "BC" in Ship Types

### ISSUE THREAD

**Issue by 9D818F848C** [silfumus/ElectronicObserver#61]
Official designation in the game is BC via the UI setting that translates ship types:

![2018-10-26 17_20_46-electronic observer](https://user-images.githubusercontent.com/44511493/47592987-a3dce880-d943-11e8-953c-2e806f33a1b0.png)
![2018-10-26 17_21_19-electronic observer](https://user-images.githubusercontent.com/44511493/47592989-a63f4280-d943-11e8-9b2a-03b602e3156f.png)

**Comment by silfumus** [comment]
Fixed via https://github.com/silfumus/ryuukitsune.github.io/commit/4dec497d9ad548eff2434a7911d2075feb40760e
