### ISSUE TITLE
Senka display

### ISSUE THREAD

**Issue by myangelkamikaze** [silfumus/ElectronicObserver#67]
The senka tooltip is bugged after the cutoff fix
![image](https://user-images.githubusercontent.com/40002167/49492470-bda31100-f89b-11e8-8be7-0870e3cbb94b.png)
There should be "Session..." above daily but it's missing. The cause of the error is probably data being logged in local time while the cutoff is calculated in JST (it showed up after local time was changed to JST and a new  data entry was made), but I couldn't check this out in detail so there might be more to it.

**Comment by silfumus** [comment]
Is it still bugged?
I believe it was temporary artifact from the cutoff change and it shouldn't affect senka calculation for the next day onwards.
