### ISSUE TITLE
Suggestion: Dark mode

### ISSUE THREAD

**Issue by silfumus** [silfumus/ElectronicObserver#70]
Submitter: NTolegna
Email: kappadresse@gmail.com
Hi ! Just a little suggestion: simply add a dark mode since EO is completly white, it would be nice for the user's eyes at night !

**Comment by myangelkamikaze** [comment]
There is a dark theme but the instructions for it kinda got buried
![image](https://user-images.githubusercontent.com/40002167/49698316-7b643180-fc05-11e8-8d16-841fbe0466a9.png)

**Comment by silfumus** [comment]
I'll add options to config panel to switch between light and dark mode.
