### ISSUE TITLE
Missing TLs

### ISSUE THREAD

**Issue by ac410** [silfumus/ElectronicObserver#8]
Translations are missing for 
Quest names
Ship names
Equipment
Enemy fleet details

**Comment by silfumus** [comment]
Could you confirm whether it has been fixed yet?

**Comment by ac410** [comment]
TLs are still missing from first glance, but mousing over details for quests give a basic translation underneath and all other UI details are translated. Except for allied and enemy ship names, equips, enemy equips. It is enough for me to work with efficiently.

**Comment by silfumus** [comment]
May I know what system language your Windows run on?

**Comment by ac410** [comment]
I have Windows format and Location in Japanese. So I messed around a little, and the issue seems to be related to having format in Japanese, location doesn't affect anything. TLs will still switch if you DL and run first time in English format, then switch to Japanese. So the fix is to not use Japanese date/time format, any other format is fine.
