### ISSUE TITLE
Can't distinguish between completed missions in the mission window

### ISSUE THREAD

**Issue by Memory-of-Snow** [silfumus/ElectronicObserver#84]
The Wiki seems to distinguish "accomplished" missions by checkboxes, but the checkboxes don't show up.
Please let me know if there is a solution or workaround.

![2022y01m29d_145053930](https://user-images.githubusercontent.com/98633948/151649439-3f94f9ca-8d97-4cd2-b2e1-aa0ad34bb021.jpg)

**Comment by myangelkamikaze** [comment]
This looks like it should go to https://github.com/gre4bee/ElectronicObserver.

**Comment by Memory-of-Snow** [comment]
Thx
